### ISSUE TITLE
Changing the Angular favicon icon from the titlebar of project

### ISSUE THREAD

**Issue by meetcric** [meetcric/myblog#1]
Steps to install project on your local machine:-
1.Clone the repo
2.cd myblog
3.npm install
4.cd angular-src
5.ng serve
Enjoy!!Happy coding

**Comment by amandachagas** [comment]
Lets try this one!

**Comment by meetcric** [comment]
Yup!!Go for it.

**Comment by meetcric** [comment]
Any update? @amandachagas
