### ISSUE TITLE
Any color changes to UI which is more attractive

### ISSUE THREAD

**Issue by meetcric** [meetcric/myblog#5]

**Comment by trilemaestro92** [comment]
I'd like to try this one.

**Comment by meetcric** [comment]
go on!!

**Comment by mShreyasKumar** [comment]
Hi @meetcric how do you run the application locally

**Comment by meetcric** [comment]
Steps to run project on your local machine:-
1.Clone the repo
2.cd myblog
3.npm install
4.cd angular-src
5.ng serve (install angular-cli on your machine before executing this command)
Enjoy!!Happy coding @mShreyasKumar

**Comment by mShreyasKumar** [comment]
Thank you for the updates @meetcric
